from brain import BrainRouter
from rich.console import Console

console = Console()

def test_rag_pipeline():
    console.print("[bold white]🧪 Testing OpenClaw Sovereign v2.5 Data Layer (RAG)...[/bold white]")
    
    brain = BrainRouter()
    
    # 1. Test Query that triggers Deep Context
    query = "Give me a deep history contextual analysis of the Bittensor network in 2024."
    
    console.print(f"\n[bold yellow]User Query:[/bold yellow] {query}")
    console.print("-" * 50)
    
    # This should trigger System 2 -> ContextLoader -> SN13 -> SN74
    response = brain.think(query)
    
    console.print("-" * 50)
    console.print("[bold green]Final Response generated by Brain:[/bold green]")
    console.print(response[:500] + "...") # Preview

if __name__ == "__main__":
    test_rag_pipeline()
